name: Build on Push
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "17.x"
            - name: Build & push
              run: |
                git config --global user.name 'GitHub Actions'
                git config --global user.email 'RedstoneWizard08@users.noreply.github.com'
                git checkout refs/heads/gh-pages
                yarn install
                yarn build
                rm !("out")
                mv out/* .
                rm -r out
                git add .
                git commit -m "Automated build"
                git push
