name: Build on Push
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "17.x"
            - run: |
                rm -r * .*; exit 0
                git clone https://github.com/Skyhawkbotics/website.git .
                git config --global user.name 'GitHub Actions'
                git config --global user.email 'RedstoneWizard08@users.noreply.github.com'
                git switch gh-pages
                yarn install
                yarn build
                rm !("out")
                mv out/* .
                rm -r out
                git add .
                git commit -m "Automated build"
                git push
